# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      # This hack makes hspaans/latexmk-action use lualatex:
      - run: echo "\$pdflatex = 'lualatex -file-line-error %O %S';" >> latexmkrc

      - name: Compile LateX
        uses: hspaans/latexmk-action@v1
        with:
          format: pdf
          filename: "Thesis.tex"

      - name: Push generated files to branch 'gh-pages'
        run: |
          mkdir -p static/pdf
          mv *.pdf static/pdf
          cd static/pdf
          git init -b main
          git config user.name $GITHUB_ACTOR
          git config user.email $GITHUB_ACTOR@users.noreply.github.com
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -m "[release] Publish on GitHub Pages"
          git push --force origin main:gh-pages
        if: ${{ success() }}
